name: cc_trace_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+2003

environment:
  sdk: ^3.12.2

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
